excluded:
  - Pods

disabled_rules:
  - todo
  - opening_brace

line_length: 200

variable_name:
  min_length: 1
  additional_allowed_characters: '_'

type_name:
  max_length:
    warning: 50
    error: 50

function_parameter_count: 10

cyclomatic_complexity: 30

function_body_length: 1000

type_body_length: 2000

file_length: 2000

large_tuple: 10

trailing_whitespace:
  ignores_empty_lines: true
